Repository CA-G12/SAIF-MOHAMMED-React-Class, pull requests merged in 2022-09, with the labels that each got.

#2 create react file structure and delete unnessary
  saif-mohammed-react/.gitignore
  saif-mohammed-react/README.md
  saif-mohammed-react/package-lock.json
  saif-mohammed-react/package.json
  saif-mohammed-react/public/favicon.ico
  saif-mohammed-react/public/index.html
  saif-mohammed-react/public/logo192.png
  saif-mohammed-react/public/logo512.png
  saif-mohammed-react/public/manifest.json
  saif-mohammed-react/public/robots.txt
  saif-mohammed-react/src/App.js
  saif-mohammed-react/src/index.css
  saif-mohammed-react/src/index.js
Labels: approved

#12 make search function
  saif-mohammed-react/src/App.js
  saif-mohammed-react/src/components/Navbar.jsx
  saif-mohammed-react/src/components/Post.jsx
Labels: awaiting-review

#16 add post feature and validate post and goHome function
  saif-mohammed-react/src/App.js
  saif-mohammed-react/src/components/AddPostForm.jsx
  saif-mohammed-react/src/components/Navbar.jsx
  saif-mohammed-react/src/components/Post.jsx
  saif-mohammed-react/src/index.css
Labels: awaiting-review

#17 create adding comment feature
  saif-mohammed-react/src/App.js
  saif-mohammed-react/src/components/AddCommentForm.jsx
  saif-mohammed-react/src/components/Comment.jsx
Labels: approved

#19 delete comment feature with loading comment and hanlding fetch errors
  saif-mohammed-react/src/App.js
  saif-mohammed-react/src/components/Comment.jsx
  saif-mohammed-react/src/components/Comments.jsx
  saif-mohammed-react/src/components/Posts.jsx
Labels: approved

#23 add post details to comment page
  saif-mohammed-react/src/App.js
  saif-mohammed-react/src/components/Comments.jsx
  saif-mohammed-react/src/components/Post.jsx
Labels: done

#25 14-handle-confirm-massage
  saif-mohammed-react/src/App.js
  saif-mohammed-react/src/components/Posts.jsx
Labels: approved

#28 make some css to comments,home page and add post page
  saif-mohammed-react/public/index.html
  saif-mohammed-react/src/components/AddCommentForm.jsx
  saif-mohammed-react/src/components/AddPostForm.jsx
  saif-mohammed-react/src/components/Comment.jsx
  saif-mohammed-react/src/components/Comments.jsx
  saif-mohammed-react/src/components/Navbar.jsx
  saif-mohammed-react/src/components/Post.jsx
  saif-mohammed-react/src/components/Posts.jsx
  saif-mohammed-react/src/index.css
Labels: awaiting-review

#29 make comments validtion and confirm delete message
  saif-mohammed-react/src/App.js
  saif-mohammed-react/src/index.css
Labels: approved
